name: Setup for Node CI

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: 'Setup Node.js ${{ matrix.node-version }}'
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - uses: actions/cache@v3
      id: cache-root
      with:
        path: ./node_modules
        key: ${{ runner.os }}-root-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-root-

    - uses: actions/cache@v3
      id: cache-app1
      with:
        path: ./app1/node_modules
        key: ${{ runner.os }}-app1-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-app1-

    - uses: actions/cache@v3
      id: cache-app2
      with:
        path: ./app2/node_modules
        key: ${{ runner.os }}-app2-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-app2-

    - name: cache ?
      run: |
        echo ${{ steps.cache-root.outputs.cache-hit }}
        echo ${{ steps.cache-app1.outputs.cache-hit }}
        echo ${{ steps.cache-app2.outputs.cache-hit }}

    - name: Install dependencies
      if: |
        steps.cache-root.outputs.cache-hit != 'true' ||
        steps.cache-app1.outputs.cache-hit != 'true' ||
        steps.cache-app2.outputs.cache-hit != 'true'
      shell: bash
      run: lerna bootstrap
