name: CI

on: push

jobs:
  app1-test:
    name: App1 test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/setup-node

      - name: Run test
        id: run-test
        run: lerna run test --scope app1
